"""baseline multi-tenant schema + RLS

Hand-written (not autogenerated — there's no live database yet to diff
against) baseline for the Supabase Postgres schema. Mirrors munshi/pg/models.py
table-for-table; see that file's docstring for the column-type rationale vs.
the SQLite schema this replaces.

Two things every future migration on a tenant-scoped table must repeat:
  1. `organization_id` NOT NULL referencing organizations(id) ON DELETE CASCADE.
  2. `enable_rls(table_name)` (defined below) — a table with no RLS policy is
     NOT safely isolated by default; Postgres denies all rows with RLS
     enabled and no matching policy, which fails closed, but a table that
     never got `enable_rls()` called on it has NO row-level security at all
     and is a full cross-tenant data leak. See migration plan risk #4 — CI
     should assert every tenant table in this file's TENANT_TABLES list has
     relrowsecurity = true.

Revision ID: 0001
Revises:
Create Date: 2026-07-17
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

# Every table carrying organization_id — RLS is enabled + the identical
# tenant-isolation policy is applied to each one at the end of upgrade().
TENANT_TABLES = [
    'memberships', 'login_failures', 'number_sequences', 'settings',
    'recipients', 'vehicles', 'drivers', 'transporters', 'diesel_vendors',
    'freight_rates', 'bills', 'extractions', 'extracted_invoices',
    'ledger_extractions', 'challans', 'ledger_entries', 'payments', 'audit_log',
]


def _enable_rls(table_name):
    op.execute(f'ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY')
    op.execute(f"""
        CREATE POLICY {table_name}_tenant_isolation ON {table_name}
        FOR ALL
        USING (organization_id = current_org_id())
        WITH CHECK (organization_id = current_org_id())
    """)


def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')

    # Reads the `org_id` custom claim Supabase's Auth Hook injects into every
    # JWT at token-mint time (see migration plan Section 1). Flask, talking
    # to Postgres directly rather than through PostgREST, sets the same GUC
    # itself per-transaction via munshi/pg/database.py's set_tenant_context().
    op.execute("""
        CREATE OR REPLACE FUNCTION current_org_id() RETURNS uuid
        LANGUAGE sql STABLE
        AS $$
          -- nullif() must guard the RAW setting before it's cast to jsonb:
          -- once a custom GUC name has been SET (even inside a transaction
          -- that later rolled back), Postgres leaves a placeholder behind
          -- and current_setting(..., true) returns '' instead of NULL —
          -- ''::jsonb raises "invalid input syntax for type json", which
          -- would take down every RLS-protected query, not just fail closed.
          SELECT nullif(
            nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'org_id',
            ''
          )::uuid
        $$
    """)

    op.create_table(
        'organizations',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('name', sa.Text, nullable=False),
        sa.Column('gstin', sa.Text),
        sa.Column('pan', sa.Text),
        sa.Column('address', sa.Text),
        sa.Column('state_code', sa.Text),
        sa.Column('phone', sa.Text),
        sa.Column('subscription_status', sa.Text, nullable=False, server_default='trial'),
        sa.Column('subscription_provider_id', sa.Text),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
    )
    # organizations itself: a user may only see orgs they belong to — not
    # the identical org_id-column pattern the other tables use, so it's
    # created separately from the TENANT_TABLES loop below.
    op.execute('ALTER TABLE organizations ENABLE ROW LEVEL SECURITY')
    op.execute("""
        CREATE POLICY organizations_member_read ON organizations
        FOR SELECT
        USING (id = current_org_id())
    """)

    op.create_table(
        'memberships',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('user_id', UUID(as_uuid=True), nullable=False),
        sa.Column('role', sa.Text, nullable=False, server_default='operator'),
        sa.Column('full_name', sa.Text),
        sa.Column('is_active', sa.Boolean, nullable=False, server_default='true'),
        sa.Column('must_change_password', sa.Boolean, nullable=False, server_default='false'),
        sa.Column('language', sa.Text, nullable=False, server_default='en'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('last_login', sa.DateTime(timezone=True)),
        sa.UniqueConstraint('organization_id', 'user_id'),
    )

    op.create_table(
        'login_failures',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('identifier', sa.Text, nullable=False),
        sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    )
    op.create_index('ix_login_failures_org_identifier', 'login_failures', ['organization_id', 'identifier'])

    op.create_table(
        'number_sequences',
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), primary_key=True),
        sa.Column('sequence_name', sa.Text, primary_key=True),
        sa.Column('next_value', sa.BigInteger, nullable=False, server_default='1'),
    )

    op.create_table(
        'settings',
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), primary_key=True),
        sa.Column('key', sa.Text, primary_key=True),
        sa.Column('value', sa.Text),
    )

    op.create_table(
        'recipients',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('name', sa.Text, nullable=False),
        sa.Column('address', sa.Text),
        sa.Column('gstin', sa.Text),
        sa.Column('state_code', sa.Text),
        sa.Column('freight_rate', sa.Numeric),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.UniqueConstraint('organization_id', 'name'),
    )

    op.create_table(
        'transporters',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('name', sa.Text, nullable=False),
        sa.Column('mobile', sa.Text),
        sa.Column('bank_details', sa.Text),
        sa.Column('notes', sa.Text),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.UniqueConstraint('organization_id', 'name'),
    )

    op.create_table(
        'diesel_vendors',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('name', sa.Text, nullable=False),
        sa.Column('location', sa.Text),
        sa.Column('notes', sa.Text),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.UniqueConstraint('organization_id', 'name'),
    )

    op.create_table(
        'vehicles',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('vehicle_no', sa.Text, nullable=False),
        sa.Column('transporter_id', sa.BigInteger, sa.ForeignKey('transporters.id')),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.UniqueConstraint('organization_id', 'vehicle_no'),
    )

    op.create_table(
        'drivers',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('mobile', sa.Text, nullable=False),
        sa.Column('name', sa.Text),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.UniqueConstraint('organization_id', 'mobile'),
    )

    op.create_table(
        'freight_rates',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('customer_name', sa.Text),
        sa.Column('party_code', sa.Text),
        sa.Column('location', sa.Text),
        sa.Column('dist_twy_km', sa.SmallInteger),
        sa.Column('dist_owy_km', sa.SmallInteger),
        sa.Column('lp_owy', sa.Numeric),
        sa.Column('lp_twy', sa.Numeric),
        sa.Column('trolla_owy', sa.Numeric),
        sa.Column('trolla_twy', sa.Numeric),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.UniqueConstraint('organization_id', 'customer_name', 'location'),
    )

    op.create_table(
        'bills',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('bill_no', sa.Text, nullable=False),
        sa.Column('bill_date', sa.Date),
        sa.Column('recipient_name', sa.Text),
        sa.Column('recipient_address', sa.Text),
        sa.Column('recipient_gstin', sa.Text),
        sa.Column('state_code', sa.Text),
        sa.Column('trip_type', sa.Text),
        sa.Column('vehicle_no', sa.Text),
        sa.Column('freight_type', sa.Text),
        sa.Column('delivery_month', sa.Text),
        sa.Column('client_name', sa.Text),
        sa.Column('total_amount', sa.Numeric, server_default='0'),
        sa.Column('deliveries', JSONB, server_default='[]'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('ledger_entry_id', sa.BigInteger),  # FK added after ledger_entries exists (circular ref)
        sa.Column('client_paid', sa.Boolean, server_default='false'),
        sa.Column('client_paid_date', sa.Date),
        sa.Column('client_paid_amount', sa.Numeric),
        sa.Column('client_paid_mode', sa.Text),
        sa.Column('client_paid_reference', sa.Text),
        sa.Column('hsn_sac', sa.Text, server_default='996511'),
        sa.Column('taxable_value', sa.Numeric, server_default='0'),
        sa.Column('reverse_charge', sa.Boolean, server_default='true'),
        sa.Column('place_of_supply', sa.Text),
        sa.Column('igst_pct', sa.Numeric, server_default='0'),
        sa.Column('cgst_pct', sa.Numeric, server_default='0'),
        sa.Column('sgst_pct', sa.Numeric, server_default='0'),
        sa.Column('igst_amount', sa.Numeric, server_default='0'),
        sa.Column('cgst_amount', sa.Numeric, server_default='0'),
        sa.Column('sgst_amount', sa.Numeric, server_default='0'),
        sa.Column('irn', sa.Text),
        sa.Column('irn_qr', sa.Text),
        sa.UniqueConstraint('organization_id', 'bill_no'),
    )

    op.create_table(
        'extractions',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('mode', sa.Text),
        sa.Column('status', sa.Text),
        sa.Column('note', sa.Text),
    )

    op.create_table(
        'extracted_invoices',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('extraction_id', sa.BigInteger, sa.ForeignKey('extractions.id', ondelete='CASCADE')),
        sa.Column('file_name', sa.Text),
        sa.Column('seq', sa.SmallInteger),
        sa.Column('raw_json', JSONB),
        sa.Column('edited_json', JSONB),
        sa.Column('error', sa.Text),
    )

    op.create_table(
        'ledger_extractions',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('source_image', sa.Text),
        sa.Column('page_date', sa.Date),
        sa.Column('raw_json', JSONB),
        sa.Column('edited_json', JSONB),
        sa.Column('status', sa.Text, server_default='pending'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
    )

    op.create_table(
        'challans',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('lr_no', sa.Text),
        sa.Column('challan_date', sa.Date),
        sa.Column('consignor_name', sa.Text),
        sa.Column('consignor_address', sa.Text),
        sa.Column('consignee_name', sa.Text),
        sa.Column('consignee_address', sa.Text),
        sa.Column('from_city_state', sa.Text),
        sa.Column('to_city_state', sa.Text),
        sa.Column('invoice_no', sa.Text),
        sa.Column('invoice_date', sa.Date),
        sa.Column('consignment_value', sa.Numeric),
        sa.Column('gst_number', sa.Text),
        sa.Column('no_of_articles', sa.Text),
        sa.Column('description', sa.Text),
        sa.Column('value_of_goods', sa.Numeric),
        sa.Column('weight_kg', sa.Numeric),
        sa.Column('del_no', sa.Text),
        sa.Column('shipment_no', sa.Text),
        sa.Column('cost_no', sa.Text),
        sa.Column('seal_no', sa.Text),
        sa.Column('driver_name', sa.Text),
        sa.Column('driver_mobile', sa.Text),
        sa.Column('truck_no', sa.Text),
        sa.Column('gate_in_time', sa.DateTime(timezone=True)),
        sa.Column('gate_out_time', sa.DateTime(timezone=True)),
        sa.Column('lane_transit_time', sa.Text),
        sa.Column('expected_arrival', sa.DateTime(timezone=True)),
        sa.Column('source_image', sa.Text),
        sa.Column('raw_extraction', JSONB),
        sa.Column('confidence_json', JSONB),
        sa.Column('status', sa.Text, server_default='open'),
        sa.Column('notes', sa.Text),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.Column('ledger_entry_id', sa.BigInteger),  # FK added after ledger_entries exists (circular ref)
        sa.Column('pod_doc_no', sa.Text),
        sa.UniqueConstraint('organization_id', 'lr_no'),
    )

    op.create_table(
        'ledger_entries',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('challan_id', sa.BigInteger, sa.ForeignKey('challans.id')),
        sa.Column('entry_date', sa.Date),
        sa.Column('gr_no', sa.Text),
        sa.Column('vehicle_no', sa.Text),
        sa.Column('station', sa.Text),
        sa.Column('shipment_no', sa.Text),
        sa.Column('trip_type', sa.Text, server_default='One Way'),
        sa.Column('mt_qty', sa.Numeric),
        sa.Column('freight', sa.Numeric, server_default='0'),
        sa.Column('advance_cash', sa.Numeric, server_default='0'),
        sa.Column('advance_account', sa.Numeric, server_default='0'),
        sa.Column('diesel', sa.Numeric, server_default='0'),
        sa.Column('diesel_vendor_id', sa.BigInteger, sa.ForeignKey('diesel_vendors.id')),
        sa.Column('transporter_id', sa.BigInteger, sa.ForeignKey('transporters.id')),
        sa.Column('pod_received', sa.Boolean, server_default='false'),
        sa.Column('pod_date', sa.Date),
        sa.Column('pod_image', sa.Text),
        sa.Column('paid', sa.Boolean, server_default='false'),
        sa.Column('paid_date', sa.Date),
        sa.Column('paid_mode', sa.Text),
        sa.Column('paid_amount', sa.Numeric),
        sa.Column('paid_reference', sa.Text),
        sa.Column('remarks', sa.Text),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True)),
        sa.Column('bill_id', sa.BigInteger, sa.ForeignKey('bills.id')),
        sa.Column('weight_kg', sa.Numeric),
    )

    # Circular FKs, added now that both sides exist.
    op.create_foreign_key('fk_bills_ledger_entry_id', 'bills', 'ledger_entries', ['ledger_entry_id'], ['id'])
    op.create_foreign_key('fk_challans_ledger_entry_id', 'challans', 'ledger_entries', ['ledger_entry_id'], ['id'])

    op.create_table(
        'payments',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('party_type', sa.Text, nullable=False),
        sa.Column('party_key', sa.Text, nullable=False),
        sa.Column('payment_date', sa.Date, nullable=False),
        sa.Column('amount', sa.Numeric, nullable=False),
        sa.Column('mode', sa.Text),
        sa.Column('reference', sa.Text),
        sa.Column('notes', sa.Text),
        sa.Column('source', sa.Text, server_default='manual'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('created_by', sa.Text),
    )
    # Matches app.py's SQLite index on (party_type, party_key) — the hot path
    # for get_party_balance().
    op.create_index('ix_payments_org_party', 'payments', ['organization_id', 'party_type', 'party_key'])
    op.create_index('ix_payments_org_date', 'payments', ['organization_id', 'payment_date'])

    op.create_table(
        'audit_log',
        sa.Column('id', sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column('organization_id', UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False),
        sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('user_name', sa.Text),
        sa.Column('action', sa.Text),
        sa.Column('entity', sa.Text),
        sa.Column('entity_id', sa.BigInteger),
        sa.Column('summary', sa.Text),
        sa.Column('changes', JSONB),
    )
    op.create_index('ix_audit_log_org_entity', 'audit_log', ['organization_id', 'entity', 'entity_id'])
    op.create_index('ix_audit_log_org_occurred', 'audit_log', ['organization_id', 'occurred_at'])

    for table_name in TENANT_TABLES:
        _enable_rls(table_name)


def downgrade():
    for table_name in reversed(TENANT_TABLES):
        op.execute(f'DROP POLICY IF EXISTS {table_name}_tenant_isolation ON {table_name}')
    op.drop_table('audit_log')
    op.drop_table('payments')
    op.drop_constraint('fk_challans_ledger_entry_id', 'challans', type_='foreignkey')
    op.drop_constraint('fk_bills_ledger_entry_id', 'bills', type_='foreignkey')
    op.drop_table('ledger_entries')
    op.drop_table('challans')
    op.drop_table('ledger_extractions')
    op.drop_table('extracted_invoices')
    op.drop_table('extractions')
    op.drop_table('bills')
    op.drop_table('freight_rates')
    op.drop_table('drivers')
    op.drop_table('vehicles')
    op.drop_table('diesel_vendors')
    op.drop_table('transporters')
    op.drop_table('recipients')
    op.drop_table('settings')
    op.drop_table('number_sequences')
    op.drop_table('login_failures')
    op.drop_table('memberships')
    op.execute('DROP POLICY IF EXISTS organizations_member_read ON organizations')
    op.drop_table('organizations')
    op.execute('DROP FUNCTION IF EXISTS current_org_id()')
